### ISSUE TITLE
configuration values for Quads

### ISSUE THREAD

**Issue by fils** [ad-freiburg/qlever-control#100]
When using a Qlever Configuration file how do I pass the required parameters to inform the system these are quads?

I have 

```
[index]
INPUT_FILES     = odis.nq
CAT_INPUT_FILES = cat ${INPUT_FILES}
SETTINGS_JSON   = { "ascii-prefixes-only": false, "num-triples-per-batch": 100000 }
```

based on the Olympics example.  Not sure the parameters to add for quads.

Thanks

**Comment by Qup42** [comment]
You can specify this using `FORMAT` in the `data` section. The valid formats are `ttl`, `nt` and `nq`. This configuration option is used in the [dblp QLeverfile](https://github.com/ad-freiburg/qlever-control/blob/dd74d182a9f6d0f548eab5c2f97a1c840798998f/src/qlever/Qleverfiles/Qleverfile.dblp#L16). So for you this could be
```ini
[data]
...
FORMAT = nq
```

**Comment by fils** [comment]
works great..   thank you very much
