### ISSUE TITLE
need for quotes

### ISSUE THREAD

**Issue by WolfgangFahl** [ad-freiburg/qlever-control#3]
I tried setting:
```
RDF_FILES        = latest-all.ttl.bz2 latest-lexemes.ttl.bz2
CAT_FILES        = "bzcat ${RDF_FILES}"
```
and ended up
```
qlever index
```
trying to
```
bzcat  | IndexBuilderMain -F ttl -K wikidata -f - -i wikidata -s wikidata.settings.json | tee wikidata.index-log.txt
```
so it seem quotes are mandatory when adding mulitple entries

**Comment by hannahbast** [comment]
Yes, the quotes are mandatory in that case.

The reason is that the `Qleverfile` interprets the assignments like it would interpret an assignment in the shell, except that it allows whitespace around the `=`. I am not sure whether automatically adding quotes is a good idea.

**Comment by WolfgangFahl** [comment]
@hannahbast  this issue is just a request to mention the fact in the documentation and give an example for multiples files as in the wikidata case. If i remember there was some need of sorting at a time is this still the case of will the QLeverFile with the above lines do? 

the second attempt with this setup is just running see https://wiki.bitplan.com/index.php/WikiData_Import_2022-05-22

**Comment by hannahbast** [comment]
@WolfgangFahl Note that you can add an argument to the initial call to `. qlever`. For example, you can call `. qlever wikidata` and then you will get a `Qleverfile` tailor-made for Wikidata. Also note that you can do `qlever download-data` to get the data. So if you are bold, you could do something like the following and just let it run and then you have an index after a day or so (on a reasonably modern PC):

```
mkdir wikidata-latest && cd wikidata-latest
. qlever wikidata
qlever download-data index
```

**Comment by WolfgangFahl** [comment]
thx - i might try this as soon as one of the attempts will work again. https://wiki.bitplan.com/index.php/WikiData_Import_2022-05-22 IMHO didn't finish properly due to another reason see reopened #563
