### ISSUE TITLE
Example scientists Qleverfile needs updating

### ISSUE THREAD

**Issue by azaroth42** [ad-freiburg/qlever-control#34]
It seems to use perhaps an older style shell variables approach without any configuration headings.
Trying to index it with `qlever index` results in 

```
Error parsing Qleverfile `Qleverfile`: Error parsing Qleverfile: File contains no section headers.
file: PosixPath('Qleverfile'), line: 11
'DB                = scientists\n'
```

(Also there are a number of issues with the scientists.nt file, mostly "s inside the URIs)

**Comment by hannahbast** [comment]
@azaroth42 Thanks for pointing that out to us, Rob. The Qleverfile was outdated and I just committed an updated version. Please try again (via `git pull` if you use the GitHub code, or via `pip install --upgrade qlever` if you use the pypi package).

**Comment by azaroth42** [comment]
Worked perfectly, thank you!
