### ISSUE TITLE
IndexBuilderMain crashes due to incorrect --stxxl-memory parameter format

### ISSUE THREAD

**Issue by arcangelo7** [ad-freiburg/qlever-control#35]
#### Description

When running the `qlever index` command using the `qlever_control` framework, I encountered an issue where the indexing process crashes without providing a clear error message. After detailed logging and investigation, I discovered that the problem is caused by the `--stxxl-memory` parameter format. If the memory value is specified with the "G" suffix (e.g., `5G`), the process crashes. The parameter should be provided as a plain number without the "G" (e.g., `5`).

#### Steps to Reproduce

1. Set up the QLever environment and prepare the QLeverfile with the following configuration:
    ```ini
    [data]
    NAME              = oc_meta
    BASE_URL          = https://w3id.org/oc/meta
    DESCRIPTION       = OpenCitations Meta stores and delivers bibliographic metadata for all publications involved in the OpenCitations Index.
    TEXT_DESCRIPTION  = All literals, search with FILTER CONTAINS(?var, "...")

    [index]
    INPUT_FILES = qlever_input_openalex/*
    CAT_INPUT_FILES = find qlever_input_openalex/ -type f | xargs cat
    SETTINGS_JSON   = { "ascii-prefixes-only": false, "num-triples-per-batch": 100000 }
    TEXT_INDEX = from_literals

    [server]
    PORT               = 7006
    MEMORY_FOR_QUERIES = 5G
    CACHE_MAX_SIZE     = 2G
    TIMEOUT            = 30s

    [runtime]
    SYSTEM = docker
    IMAGE  = docker.io/adfreiburg/qlever:latest

    [ui]
    UI_CONFIG = oc_meta
    ```

2. Run the `qlever index` command.

#### Expected Behavior

The indexing process should complete successfully without crashing.

#### Actual Behavior

The process crashes, and the following error message is logged:

```sh
Error in command-line argument: bad lexical cast: source type value could not be interpreted as target
Options for IndexBuilderMain:
...
-m [ --stxxl-memory-gb ] arg The amount of memory in GB to use for
sorting during the index build.
Decrease if the index builder runs out
of memory.
...
```

#### Investigation and Findings

Detailed logging revealed that the `--stxxl-memory` parameter should be provided without the "G" suffix. The following command works as expected:

```sh
IndexBuilderMain -F ttl -f - -i oc_meta -s oc_meta.settings.json --text-words-from-literals --stxxl-memory 5 | tee oc_meta.index-log.txt
```

#### Suggested Fix

Modify the QLeverfile configuration or the script to remove the "G" suffix from the --stxxl-memory parameter. Ensure that the value is passed as a plain number.

```sh
index_cmd = f"{args.cat_input_files} | {args.index_binary} -F ttl -f - -i {args.name} -s {args.name}.settings.json --text-words-from-literals --stxxl-memory {args.stxxl_memory.replace('G', '')} | tee {args.name}.index-log.txt"
```

Alternatively, update the provided version of the QLeverfile to include the STXXL_MEMORY parameter without the "G" suffix, or handle this within the code to prevent similar issues for other users.

#### Environment

- **QLever Control Version**: Latest
- **Operating System**: Debian 12

**Comment by Qup42** [comment]
The command line option `--stxxl-memory-gb` no longer exists. It looks like you're running an old version of QLever (pre https://github.com/ad-freiburg/qlever/pull/1067). Can you do a `docker pull docker.io/adfreiburg/qlever:latest` and then retry if the issue persists?

**Comment by arcangelo7** [comment]
Thank you for your response.

In my QLeverfile, I have specified the latest Docker image (docker.io/adfreiburg/qlever:latest). The issue I'm experiencing is not with QLever itself, but with QLever Control. I installed QLever Control following the instructions in the README using pip. Additionally, I verified that the QLever Control version I installed via pip is the latest available on PyPI, version 0.5.2

**Comment by hannahbast** [comment]
@Qup42 It seems that people are frequently stumbling over this. It would be easy to add an automatic docker pull to the `index` and `start` command. Do you think we should do it? Is there a significant downside?

**Comment by hannahbast** [comment]
Here is one valid reason. Consider the following scenario:

1. The index is built with `adfreiburg/qlever:latest` (the default)
2. There is a new version of QLever with an index-breaking change
3. You start the server with the old index
4. Then with an automatic pull, the start will fail

That is unlikely to happen when frequently rebuilding the index. It is more likely when using the same index for a long time.

Then again, it's not that tragic for two reasons. First, when `start` fails because of that, there is a good error message, which tells you to either rebuild the index or use an older image (and it even tells you which one). Second, the rate of index-breaking changes to QLever decreases significantly over time.

**Comment by Qup42** [comment]
Given that this is a common stumbling block, I think that, that the benefits of an automatic pull outweigh. The only real downside that I see is that it will make the docker commands slower. On my machine its a delay of ~1.5s for the two methods 2 `docker pull` and `--pull always`. 

On breaking changes between versions: 
If one wants/needs to use a specific version one can always use the tag for that commit (e.g. [commit-0ff6f76](https://hub.docker.com/layers/adfreiburg/qlever/commit-0ff6f76/images/sha256-bca3a1b6c00414d4d60819c3e249a20cd30e06e54192719b0245445fb1bf085d)) or [pull the image by its digest](https://docs.docker.com/reference/cli/docker/image/pull/#pull-an-image-by-digest-immutable-identifier) (e.g. `adfreiburg/qlever:latest@sha256:9bda0d91acc7959713ad99a0cf5df1bdf360ab2af9ddc5c1d2e5c54c1fb4b65a`). With the digest one will always get that exact version. The tags that correspond to commits are also not changed for QLever.
With the commit hash from the server's error message it is possible to configure a compatible image.

**Comment by arcangelo7** [comment]
After further investigation, I confirmed that I was not using the latest version of the Docker image. Performing a docker pull docker.io/adfreiburg/qlever:latest has resolved the issue completely. The indexing process now runs without any errors related to the --stxxl-memory parameter format. I can confirm that this solution works, and I can consider this issue resolved
