### ISSUE TITLE
Feature Request: Support configuration parameter for specifying input file format in qlever index

### ISSUE THREAD

**Issue by arcangelo7** [ad-freiburg/qlever-control#36]
#### Description

Currently, the input file format for `qlever index` is hardcoded to Turtle (`ttl`). It would be beneficial to support other formats such as N-Triples (`nt`).

#### Request

Please add a configuration parameter to the QLeverfile to specify the input file format. This will allow users to handle various RDF file formats.

#### Suggested Solution

Add a `FILE_FORMAT` parameter in the QLeverfile with a default value of `ttl`:

```ini
[index]
FILE_FORMAT = ttl  # New parameter to specify file format
```

Modify the command to use this parameter:

```python
file_format = args.file_format or "ttl"
index_cmd = (f"{args.cat_input_files} | {args.index_binary}"
             f" -F {file_format} -f -"
             f" -i {args.name}"
             f" -s {args.name}.settings.json")
```

This feature will make QLever more versatile and adaptable to various data sources. Thank you for considering this request.

**Comment by Qup42** [comment]
QLever currently only supports Turtle and N-Triples (which is a subset of Turtle). Turtle and N-Triples are handled the same by QLever while indexing. So while this would have no effect right now, it might still be good for future-proofing.

**Comment by arcangelo7** [comment]
Thank you for the clarification! I'll close the issue
