### ISSUE TITLE
I don't see my graph in the UI

### ISSUE THREAD

**Issue by tomersagi** [ad-freiburg/qlever-control#43]
I indexed my graph successfully, started the GUI successfully, but in the GUI I can only see the Qlever example graphs. How do I query my graph? My graph's name is MEHDIE. 

![image](https://github.com/ad-freiburg/qlever-control/assets/8471397/a149d3b1-e012-4c1b-9ab2-0f793881a38e)

This is the content of my Qlevcerfile.mehdie:

```
[data]
NAME         = mehdie
GET_DATA_URL = index/*.ttl
GET_DATA_CMD = .
VERSION      = $$(date -r dblp.ttl.gz +"%d.%m.%Y %H:%M" || echo "NO_DATE")
DESCRIPTION  = MEHDIE KG

[index]
INPUT_FILES     = *.ttl
CAT_INPUT_FILES = cat /index/output.ttl
SETTINGS_JSON   = { "ascii-prefixes-only": false, "num-triples-per-batch": 10000, "prefixes-external": [""] }

[server]
PORT               = 7015
ACCESS_TOKEN       = ${data:NAME}
MEMORY_FOR_QUERIES = 8G
CACHE_MAX_SIZE     = 5G

[runtime]
SYSTEM = docker
IMAGE  = docker.io/adfreiburg/qlever:latest

[ui]
HOST_NAME = localhost
UI_PORT = 7070
UI_CONFIG = mehdie
```

This is the command I am using to start the UI and the system response:
```
qlever --qleverfile Qleverfile.mehdie ui --ui_port 7070 --host-name localhost

Command: ui

Stop running containers
docker pull -q docker.io/adfreiburg/qlever-ui
docker run -d --publish 7070:7000 --name qlever.ui.mehdie docker.io/adfreiburg/qlever-ui
docker exec -it qlever.ui.mehdie bash -c "python manage.py configure mehdie http://localhost:7015"

```

**Comment by hannahbast** [comment]
@tomersagi When you run `qlever ui ...`, then after the lines you posted, there should be a line:

```The QLever UI should now be up at http://localhost:7070 ...You can log in as QLever UI admin with username and passwort "demo"```

Is this line not displayed for you?

**Comment by tomersagi** [comment]
It is displayed.

**Comment by hannahbast** [comment]
And then you go to the URL http://localhost:7070 ? The screenshot above looks like it's from https://qlever.cs.uni-freiburg.de .

**Comment by tomersagi** [comment]
no, it's from localhost:7070

**Comment by tomersagi** [comment]
I also now found that I can add my server to the GUI using this interface:

![image](https://github.com/ad-freiburg/qlever-control/assets/8471397/969377de-44be-448a-bfcf-611777e05ae1)

But is there a way to persist this so that when I restart the GUI it will connect to my qlever backend?

**Comment by hannahbast** [comment]
@tomersagi The `qlever ui` command is a quick way to get a UI for one of the datasets with pre-configured Qleverfiles (or your own) and play around with it a bit.

If you want a persistent UI, you should clone https://github.com/ad-freiburg/qlever-ui, build the docker image, and run it. Then you can configure your own backend just as you did now. The configuration is stored in a sqlite3 database in `db/qleverui.sqlite3`. 

The UI is still work in progress and not properly documented yet, sorry.

**Comment by tomersagi** [comment]
ok, but I will have the same problem in the cloned UI, wont I? once I stop the container, the backend details are lost? Is there a way to configure them so they get loaded with the container?

**Comment by Qup42** [comment]
If you run it in Docker you will have to store the DB file in a bind mount or a volume. If you clone and run it locally the DB file will also persist across restarts.

**Comment by tomersagi** [comment]
Got it thanks.
