### ISSUE TITLE
qlever ui port 7000 issue on mac

### ISSUE THREAD

**Issue by Stiksels** [ad-freiburg/qlever-control#49]
**Issue description**
When following the onboarding guide with the olympics dataset, every step works fine, except the `qlever ui` command generates an incorrect URL

**Logs**

```
Command: ui

Stop running containers
docker pull -q docker.io/adfreiburg/qlever-ui
docker run -d --publish 7000:7000 --name qlever.ui.olympics docker.io/adfreiburg/qlever-ui
docker exec -it qlever.ui.olympics bash -c "python manage.py configure olympics http://1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa:7019"

docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:7000 -> 0.0.0.0:0: listen tcp 0.0.0.0:7000: bind: address already in use.
Error response from daemon: Container ec0ea36480267e408206f84edd0f6a6b1065af9dde1ef5ec0a54de304b3814cf is not running
The QLever UI should now be up at http://1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa:7000 ...You can log in as QLever UI admin with username and passwort "demo"
```

**cause (?)**
* The issue with running process on port 7000 on a Mac: https://github.com/cookiecutter/cookiecutter-django/issues/3499
* by disabling airplay receiver, port 7000 is available for qlever ui

**logs**
```
Command: ui

Stop running containers
docker pull -q docker.io/adfreiburg/qlever-ui
docker run -d --publish 7000:7000 --name qlever.ui.olympics docker.io/adfreiburg/qlever-ui
docker exec -it qlever.ui.olympics bash -c "python manage.py configure olympics http://1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa:7019"

The QLever UI should now be up at http://1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa:7000 ...You can log in as QLever UI admin with username and passwort "demo"
```

* following the URL from the logs doesn't work

**logs docker container qlever.ui.olympics**
```
2024-06-28 10:43:44 [2024-06-28 08:43:44 +0000] [1] [INFO] Starting gunicorn 21.2.0
2024-06-28 10:43:44 [2024-06-28 08:43:44 +0000] [1] [INFO] Listening at: http://0.0.0.0:7000 (1)
2024-06-28 10:43:44 [2024-06-28 08:43:44 +0000] [1] [INFO] Using worker: sync
2024-06-28 10:43:44 [2024-06-28 08:43:44 +0000] [13] [INFO] Booting worker with pid: 13
2024-06-28 10:43:45 [2024-06-28 08:43:45 +0000] [14] [INFO] Booting worker with pid: 14
2024-06-28 10:43:45 [2024-06-28 08:43:45 +0000] [15] [INFO] Booting worker with pid: 15
```

* navigating to http://0.0.0.0:7000 doesn't work either
* navigating to http://localhost:7000 does show a qlever ui

**error message in qlever ui**
* When executing any of the example queries, the following error is returned
```
Error processing query
Cannot reach http://1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa:7019. The most common cause is that the QLever server is down. Please try again later and contact us if the error persists
```

![image](https://github.com/ad-freiburg/qlever-control/assets/6908947/f1ea4a0d-b1d6-40aa-aef3-9a854b2a3f42)

![image](https://github.com/ad-freiburg/qlever-control/assets/6908947/f7422da9-7c52-48bd-b3ac-3707e378619a)

**Comment by Qup42** [comment]
You can set port with `--ui_port` and a hostname with `--host-name`. So e.g. `qlever ui --ui_port 7001 --host-name localhost` could work.

**Comment by Qup42** [comment]
Using `socket.getfqdn()` as the default value for the host name seems to cause some problems. It can also cause problems with VPNs. @hannahbast what is the reason for using this default? Does something speak against using `localhost` or `127.0.0.1`?

**Comment by Stiksels** [comment]
Thanks for the quick reply! This works perfect: `qlever ui --ui_port 7001 --host-name localhost`

🤔 I do run a VPN, so that might indeed interefered as well

**Comment by joka921** [comment]
Thanks @Stiksels  for reporting and @Qup42  for analyzing.
I have also already stumbled upon the host-name issue.
@hannahbast I think the ui port can already be set in the QLever file, what can we do here for the host-name settings? 
And also I think there's room here for a project for people who prefer to program in Python:)

**Comment by Qup42** [comment]
@joka Both can be set in the Qleverfile:
```
[server]
HOST_NAME = 127.0.0.1

[ui]
UI_PORT = 7002
```

**Comment by ktk** [comment]
Looks like recent MacOS versions use 7000 for:

```
lsof -i :7000
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ControlCe 605  xxx    8u  IPv4 0x681e61f93c1ee0c3      0t0  TCP *:afs3-fileserver (LISTEN)
ControlCe 605  xxx    9u  IPv6 0x7048d74159929df6      0t0  TCP *:afs3-fileserver (LISTEN)
```

Which seems to be something related to [AirPlay, see a related issue somewhere else](https://github.com/cookiecutter/cookiecutter-django/issues/3499). It might be a good idea to change the default to something else.

**Comment by Qup42** [comment]
That's a very good remark @ktk. A port that is already used by default on mac isn't suitable as a default port. Nonetheless any port we choose could already be used by something else. I have two ideas to deal with this better in the future:
- Try to check if the chosen port is already bound. If it is bound display a warning that guides the user towards setting a custom port.
- Try to check if the chosen port is already bound. If it is bound, find a random port to bind to.

**Comment by ktk** [comment]
I would vote for reporting & failing, magic here is more confusing IMO
