### ISSUE TITLE
download marked as successful even when incomplete

### ISSUE THREAD

**Issue by WolfgangFahl** [ad-freiburg/qlever-control#80]
See failed https://wiki.bitplan.com/index.php/Wikidata_Import_2024-10-24
When downloading the latest dump:
```
[latest-all.ttl.bz2](https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.ttl.bz2)                                 23-Oct-2024 15:41        113759486521
```
The qlever script reports:
```
 97  482M   97  472M    0     0  4680k      0  0:01:45  0:01:43  0:00:02 4743k
 98  482M   98  476M    0     0  4680k      0  0:01:45  0:01:44  0:00:01 4691k
 99  482M   99  481M    0     0  4675k      0  0:01:45  0:01:45 --:--:-- 4588k
100  482M  100  482M    0     0  4675k      0  0:01:45  0:01:45 --:--:-- 4537k

Download successful, total file size: 58,697,938,866 bytes
```
end continues the work as if nothing was wrong we get
```
2024-10-24 21:43:05.296 - INFO: Triples sorted: 10,242,062,336 [average speed 3.5 M/s, last batch 5.8 M/s, fastest 12.0 M/s, slowest 0.0 M/s] 
...
QLever indexing process completed at Thu Oct 24 09:43:15 PM CEST 2024
```
Showing too few triple

The server is started with the incomplete import effectively trying to overrde our working copy which is only prevented by 
```
QLever server already running on port 7001
```

**Comment by hannahbast** [comment]
@WolfgangFahl Does this issue still persist? There have been multiple fixes regarding this over the last month. In particular, there was a typo in the `GET_DATA_CMD` in the Qleverfile for Wikidata, which was fixed by d4902b9f8cccaa1f4012656848e3f0b131746538 .

**Comment by WolfgangFahl** [comment]
https://wiki.bitplan.com/index.php/Wikidata_Import_2024-11-16 also failed.

**Comment by hannahbast** [comment]
@WolfgangFahl It says `qlever 0.5.3`. That is the version from June 29. The latest version is `0.5.12`.

**Comment by WolfgangFahl** [comment]
@hannahbast thanks for the hint - the 0.5.3 import seems to be o.k. i still upgraded
